title: naildrivin5.com - David Bryant Copeland's Website
email: davec@naildrivin5.com
description: >
  This the website of programmer and author David Bryant Copeland.
  It includes his blog, bio, talks, and other resources.
baseurl: ""
url: "http://naildrivin5.com"
production_url: "http://naildrivin5.com"
twitter_username: davetron5000
github_username:  davetron5000
atom_path: "atom.xml"
author: "David Bryant Copeland"
subscribe_rss: /atom.xml

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

highlighter: pygments
date_format: "ordinal"
permalink: /blog/:year/:month/:day/:title.html
paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
titlecase: true       # Converts page and post titles to tilecase
Google_analytics_tracking_id: 'UA-10518541-5'
excerpt_separator: '<!-- more -->'
